version: '3.7'
services:
  customers:
    container_name: customers_service
    restart: always
    build:
      dockerfile: Dockerfile # The name of the docker config file
      context: ./customers # Where the docker config file is located
    volumes:
      - /app/node_modules
      - ./customers:/app
    ports:
      - '30502:3000'
    links:
      - mongo
    environment:
      # - dev=1
      # - db_service_name=mongo
      - MONGO_URI=mongodb://mongo:27017/youverifyDb
      - JWT_KEY=nh7dd4456vhbgkjvdDWQZXMKOY6FDEAmkbZMOPI
      # - db_retry_time=3000
  products:
    container_name: products_service
    restart: always
    build:
      dockerfile: Dockerfile # The name of the docker config file
      context: ./products
    volumes:
      - /app/node_modules
      - ./products:/app
    ports:
      - '30503:3000'
    links:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/youverifyDb
      - JWT_KEY=nh7dd4456vhbgkjvdDWQZXMKOY6FDEAmkbZMOPI
  orders:
    container_name: orders_service
    restart: always
    build:
      dockerfile: Dockerfile # The name of the docker config file
      context: ./orders
    volumes:
      - /app/node_modules
      - ./orders:/app
    ports:
      - '30504:3000'
    links:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/youverifyDb
      - JWT_KEY=nh7dd4456vhbgkjvdDWQZXMKOY6FDEAmkbZMOPI
  payments:
    container_name: payments_service
    restart: always
    build:
      dockerfile: Dockerfile # The name of the docker config file
      context: ./payments
    volumes:
      - /app/node_modules
      - ./payments:/app
    ports:
      - '30505:3000'
    links:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/youverifyDb
      - JWT_KEY=nh7dd4456vhbgkjvdDWQZXMKOY6FDEAmkbZMOPI
      - RABBITMQ_CONNECTION_STRING=amqp://guest:guest@rabbitmq:5672

  rabbitmq:
    image: rabbitmq:3.8.9-management
    ports:
      - 5672:5672
      - 15672:15672
    # volumes:
    #   - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
    #   - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
  mongo:
    image: mongo
    volumes:
      - ./db:/data/db
    ports:
      - '27017:27017'
